### ISSUE TITLE
Can this be made compatible with Nova 3?

### ISSUE THREAD

**Issue by Synchro** [mostafaznv/nova-map-field#1]
I see that this has a dependency on Nova 4.0 in composer.json, but is there anything particular that it's using that will prevent it working in Nova 3 (which I'm currently stuck with)?

While I'm here, I'd really like to see a simple way of handling `Point` types in Nova, ideally simply rendering them as a pair of text inputs for lat & long (I don't need any map functionality). I can't make the `matanyadaev/laravel-eloquent-spatial` package work in Nova, as per [this issue](https://github.com/MatanYadaev/laravel-eloquent-spatial/issues/28) in which you tagged this package.

**Comment by Synchro** [comment]
Oh, please don't go to any effort on this, I was just wondering if it was a simple thing. I should be able to update to Nova 4 in a couple of weeks; I'm stuck with 3 until then (it's a simple license issue – support has expired and the person paying is away).

Thanks for the info on the trait. Is this a general problem with Nova that every field type has to take into account, or is it a bug in Nova?

**Comment by mostafaznv** [comment]
Ok. but if you wanted any help about Nova 3, just ask. I will release a version for you.


No it's not a bug. Nova just wants to log changes into `action_events` table.
When we change that spatial fields, nova wants to log the value of column into database and it doesn't know how to convert it from that custom spatial type into string.
I think the developer of `matanyadaev/laravel-eloquent-spatial` should find a solution to handle these situation because it isn't a Nova thing. whenever we want to call getRawOriginal method or something like that, this bug happens.

**Comment by Synchro** [comment]
It would be very helpful if you could report it like that on that project. As I didn't understand the origin of the problem, the only way I could reproduce it was using Nova, and the author assumed it was a Nova problem. If you can make a much simpler test case, it would probably make it much clearer and easier for them to find a fix.

Really, don't bother with the Nova 3 thing, though thank you very much for the offer!

**Comment by mostafaznv** [comment]
Hi @Synchro 

Could you please [test](https://github.com/mostafaznv/laravel-eloquent-spatial) this package **(it's not a packagist package and you can't install it with composer commands. you should load it locally from composer.json)** and tell me if your issues with nova are gone or not?

I tried to fix `laravel-eloquent-spatial` issues and it seems everything is OK now.

Please test these items:
1. Overall package functionalities (as it worked before)
2. Compatibility with Nova
3. Check if `getDirty` and `getChanges` are working normally


If everything works normally, I can send a PR to the main repository.

**Note**: Please read [Quick Start](https://github.com/mostafaznv/laravel-eloquent-spatial#quickstart) section. It has small changes.


----
fix for https://github.com/MatanYadaev/laravel-eloquent-spatial/issues/28#issuecomment-1166249083

**Comment by Synchro** [comment]
Thanks very much for doing that, it's very kind of you.

I have incorporated your new code into the simple Nova setup I was using before, and pushed that to a private repo that you have access to. I'm still getting a problem when visiting the index page of the nova resource, the same issue I have of a Point property not being an object, and so it ends up trying to set lat/long on null. I'm not sure what I'm missing to cause that.

**Comment by mostafaznv** [comment]
> Thanks very much for doing that, it's very kind of you.
> 
> I have incorporated your new code into the simple Nova setup I was using before, and pushed that to a private repo that I have invited you to. I'm still getting a problem when visiting the index page of the Nova resource: a Point property is not an object when that loads or "invalid spatial value", so it ends up trying to set lat/long on null. I'm not sure what I'm missing to cause that.

Hi again.
I fixed it. please check update your private repo and test it again.
you must use `HasSpatialColumns` trait in your `Place` Model

**Comment by mostafaznv** [comment]
> That's perfect, thank you so much! I needed to re-add the `step('any')` option on the Nova `Number` input field to allow arbitrary fractional values, and now it's working perfectly.

Nice.
Could you please test whole functionalities?
I want to push this changes to the main repo as a PR. I want to know whether all functionalities work well

**Comment by Synchro** [comment]
I've pushed some changes to try to do that, but it's not happy. I had to do some workarounds in composer.json so that it would allow me to load a local copy of this lib so that I could allow it to run with Nova 3. I've added map Point and Polygon fields with spatial indexes, and set those up with corresponding MapPointField and MapPolygonField Nova fields, and expanded the seeder to provide a test location (and I can see correct values in the DB from that). I published assets and ran `npm install`, `npm run dev`, but then run into 2 issues:

* Trying to add a new place gives a `Attempt to read property "latitude" on null` (which I've run into before)
* There is a JS error logged in the browser `ReferenceError: Can't find variable: Vue`, which sounds quite fundamental!

**Comment by mostafaznv** [comment]
> I've pushed some changes to try to do that, but it's not happy. I had to do some workarounds in composer.json so that it would allow me to load a local copy of this lib so that I could allow it to run with Nova 3. I've added map Point and Polygon fields with spatial indexes, and set those up with corresponding MapPointField and MapPolygonField Nova fields, and expanded the seeder to provide a test location (and I can see correct values in the DB from that). I published assets and ran `npm install`, `npm run dev`, but then run into 2 issues:
> 
> * Trying to add a new place gives a `Attempt to read property "latitude" on null` (which I've run into before)
> * There is a JS error logged in the browser `ReferenceError: Can't find variable: Vue`, which sounds quite fundamental!

My own package is not compatible with Nova 3.
I just wanted you to test [this](https://github.com/mostafaznv/laravel-eloquent-spatial) package and check if it works normally after my changes or not.

I think it works well and I want to send PR to `MatanYadaev/laravel-eloquent-spatial`

**Comment by mostafaznv** [comment]
No it's not a Nova 3 compatible version. it's a fix for that ["Malformed UTF-8 characters"](https://github.com/MatanYadaev/laravel-eloquent-spatial/issues/28#issue-1154598446) bug.



-------

> Would you expect those other geo field types to work in Nova just as regular Text fields, converting to and from WKT strings or something?

Yes. but you need to modify them with `displayUsing` method as you did it in your private repo.
With these new changes, I tried to fix [these](https://github.com/MatanYadaev/laravel-eloquent-spatial/issues/28#issuecomment-1166249083) issues

**Comment by Synchro** [comment]
I've at last updated to Nova 4 and this location field is now working. Thank you for your help.
