### ISSUE TITLE
There are a way to hide the Show Details button?

### ISSUE THREAD

**Issue by SpiritSaint** [mostafaznv/nova-map-field#11]
Hi @mostafaznv 

Your package looks amazing. Do you have an idea about the issue title?

**Comment by mostafaznv** [comment]
Hi @SpiritSaint 
Thanks.

I will add a feature to hide them in future versions.

**Comment by mostafaznv** [comment]
please update to v[1.6.0](https://github.com/mostafaznv/nova-map-field/releases/tag/1.6.0)
