### ISSUE TITLE
Defaults to low precision, odd location?

### ISSUE THREAD

**Issue by Synchro** [mostafaznv/nova-map-field#12]
I've updated to 1.5, republished assets, and also updated the underlying laravel-eloquent-spatial 2.2.1 with Nova 4.12.12, and I'm seeing odd behaviour when setting a location. If I search for "London Eye" and select the first result, it gives me this (correct) location:

![Screenshot 2022-07-26 at 10 47 02](https://user-images.githubusercontent.com/81561/180965789-cd861a54-38a6-4116-8af6-82512e15910d.png)

If I save that, the location is changed to 55.5, 1.1, which is somewhere in the North Sea:

![Screenshot 2022-07-26 at 10 51 00](https://user-images.githubusercontent.com/81561/180966003-485c0b6f-3dea-43c2-81b8-e0ecc14307fe.png)

My model has the `HasSpatialColumns` trait and `SpatialBuilder` configured and has a single `Point` type field. My nova-map-field config file sets defaults (which are not where it ends up):

    'default-latitude' => 51.503285078874,
    'default-longitude' => -0.11968315000473,

My Nova resource uses a simple:

    MapPointField::make('Location'),

I reimported npm libs, regenerated assets with `npm run dev`. It doesn't generate any errors, and it doesn't seem to make any difference what location I've chosen when I try to save. Those numbers do not appear anywhere in my source.

Any idea why it might be acting this way?

**Comment by mostafaznv** [comment]
Hi @Synchro 

Thanks for the report.
I fixed it and it will be published in next version.

**Comment by mostafaznv** [comment]
please update to v[1.6.0](https://github.com/mostafaznv/nova-map-field/releases/tag/1.6.0)

**Comment by Synchro** [comment]
That's great, works as expected now, thank you.
