### ISSUE TITLE
Lat/long icon orientation in text views

### ISSUE THREAD

**Issue by Synchro** [mostafaznv/nova-map-field#14]
I just noticed that index views the location as strings with little icons beside them, but the icons have the same orientation, which I suspect isn't right?

![image](https://user-images.githubusercontent.com/81561/181472075-180ee1db-f20f-4194-bba8-43041c4c835e.png)

Inspecting the rendered source, it uses the same inline svg for both, and I see they both have the same `fa-rotate-270` class attached to them. I don't appear to have that style in my Nova installation – is it perhaps from Font Awesome? Should it be using the `rotate-` classes from tailwind?

I noticed because [this other package](https://packagist.org/packages/genealabs/nova-map-marker-field) does something similar:

![image](https://user-images.githubusercontent.com/81561/181471602-a184cacd-ac9e-4840-9d03-b8d58642bec6.png)

**Comment by mostafaznv** [comment]
Hi @Synchro 

Bug fixed.
please update the package to v[1.6.1](https://github.com/mostafaznv/nova-map-field/releases/tag/1.6.1)

**Comment by Synchro** [comment]
Perfect, thanks
