### ISSUE TITLE
Issue when updating location on resource

### ISSUE THREAD

**Issue by om0x1ar** [mostafaznv/nova-map-field#16]
Hello, I found an issue in the plugin on Laravel 9 running PHP 8.

When updating the location on a resource it comes up with an error saying "**Unable to encode attribute [original] for model [Laravel\Nova\Actions\ActionEvent] to JSON: Malformed UTF-8 characters, possibly incorrectly encoded**."

**Comment by mostafaznv** [comment]
Hi @om0x1ar 
Thanks for the report but I couldn't reproduce this bug.

Would you tell me the exact version of PHP, Laravel and NovaMapField?
