### ISSUE TITLE
Custom tile implementation

### ISSUE THREAD

**Issue by SpiritSaint** [mostafaznv/nova-map-field#17]
Hey @mostafaznv 

Thanks for previous support 

I was looking the code but i don't found anything related to implement [this](https://vue3openlayers.netlify.app/componentsguide/sources/osm/#url).

So there are a lot of map tiles that can be configured by passing a simple string like:

```
https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png
```

I wanna help on this implementation. 

Do you have some ideas about how to start to code this?. Like file names about where is the map implementation? I'm pretty sure that is [this file](https://github.com/mostafaznv/nova-map-field/blob/master/resources/js/components/form-fields/PointFormField.vue) who is responsible to render the map. That's right?

**Comment by SpiritSaint** [comment]
@mostafaznv can you send me a email to iantorres@outlook.com

I feel like that i need premium support for this. We can schedule a meeting to discuss this.

**Comment by mostafaznv** [comment]
Hi @SpiritSaint 
Write your feature-request here, I will develop it ASAP

**Comment by mostafaznv** [comment]
Hi @SpiritSaint 
Write your feature-request here, I will develop it ASAP

**Comment by SpiritSaint** [comment]
Hi @mostafaznv 

I'm creating a GPS platform so i'm facing the following stories:

- As a user i want to create/update Geofences (Polygon) ...
    - and want to drag-and-drop the shape.
    - and want to go back when i'm creating the shape.
    - and want to remove a point of the shape when i click over the point.

I'm trying to implement that on [this fork](https://github.com/SpiritSaint/nova-map-field). You can see the changes on [this link](https://github.com/mostafaznv/nova-map-field/compare/master...SpiritSaint:nova-map-field:master).

I don't know why this package saves the locations in a different order. Like longitude on latitude and latitude on longitude.

I'll leave some comments on the PR. 

Also i'm looking formulas to make you a payment on virtual coins.

If you wanna negotiate with me you can sent me a email to iantorres@outlook.com

Your code is huge appreciated and can be a useful repository for my projects.

**Comment by mostafaznv** [comment]
Thank you for the PR and your explanations.

I have a few questions about your requests:

- **and want to drag-and-drop the shape**
You can already drag all points of a polygon. is it enough? or do you want to drag all the polygon with one click?

- **and want to go back when i'm creating the shape**
I didn't understand. Do you want something like **undo**?

- **and want to remove a point of the shape when i click over the point.**
Ok. I will add a clear button to polygon field.

--------

I will work on it this weekend (here in Iran, Thursday and Friday are weekends 😄)

**Comment by SpiritSaint** [comment]
@mostafaznv I remember when my country was on heavy protests.

For moments the stuff was really hot and hard to manage. Really old ways to deal with things has been implemented for many years ago and you know. Sometimes things are really hard to change. Resistance and/or opposition are the big part of status quo protection mechanisms.

My recommendations is **keep-safe**. 
When civil movements starts and goes against the status quo many bad things can happens. 

... .

Anyways, i'm will keep an eye on what happens and see if i can do something...

______

Related to the user stories. 

- _and want to drag-and-drop the shape_ it's about move all the shape or polygon not just the polygon dots. Imagine that you click on the middle of the sape and move to the right or left. That's would be really hard.
- _and want to go back when i'm creating the shape_ it's about a undo. Like _oh, i miss click and i'll remove the last point added_.

The clear button is already implemented on my branch but again sounds really cool if we add it with translation option because can be used for many people.

**Comment by mostafaznv** [comment]
Thank you for your kind words

--------

Please update the package to [v1.7.0](https://github.com/mostafaznv/nova-map-field/tree/1.7.0)

Over last 2 days, I tried to implement the `Drag and Drop` feature. 
Because of lack of support in [vue3-openlayers](https://github.com/MelihAltintas/vue3-openlayers), it was hard to implement it but I found a solution at last. please read [this](https://github.com/mostafaznv/nova-map-field#tricks) part of documentation first.

**Comment by mostafaznv** [comment]
Undo button released under [v1.7.1](https://github.com/mostafaznv/nova-map-field/releases/tag/1.7.1)

Please update the package.

**Comment by mostafaznv** [comment]
Clear map button released under [v1.7.2](https://github.com/mostafaznv/nova-map-field/tree/1.7.2)

Please update the package.

**Comment by mostafaznv** [comment]
I added more properties to config file. so you can customize color of polygons now.

Please update the package to 1.7.3

**Comment by SpiritSaint** [comment]
Thanks @mostafaznv 

I'm setting up my coinbase account. After 7 days i'll be able to send you a payment. By the moment i can only buy 0.05 USD of bitcoin/ethereum/whatever. :(

**Comment by mostafaznv** [comment]
Hi @SpiritSaint 

I did this to help you, not to get donation. so, take it easy. no rush.

And FYI, Coinbase is experiencing some difficulties. it's better to use Binance.
