### ISSUE TITLE
Search integration

### ISSUE THREAD

**Issue by wdelfuego** [mostafaznv/nova-map-field#2]
Hey, thanks for a nice package! Works very smoothly 👍 .

When setting a geomarker on a new object, it'd be nice to be able to search for an initial address or even just a city, to speed up setting the marker correctly or make sure it's a precise address. I'm guessing it'll depend on the features of the underlying maps api whether this is something simple or very complex.

In any case, thanks a lot, curious to hear your thoughts.

**Comment by mostafaznv** [comment]
Hi @wdelfuego 

I want to add this feature in the next version and yes, It's totally depend on `OpenLayers Maps` and for now, I don't know if they have a good support for it or not. But I'm going to give it a try in next versions

**Comment by mostafaznv** [comment]
Please update the package to version 1.4.0

**Comment by wdelfuego** [comment]
Great news, looking forward to seeing it :)! Thanks!!

**Comment by wdelfuego** [comment]
By the way what geo coding service is driving the search?

**Comment by mostafaznv** [comment]
These are available providers: 

`OSM`, `MAPQUEST`, `PHOTON`, `PELIAS`, `BING`, `OPENCAGE`

for more information, please check the documentation.

**Comment by wdelfuego** [comment]
Wow, great work man 👍
