### ISSUE TITLE
Search box doesn't show up, error in console

### ISSUE THREAD

**Issue by wdelfuego** [mostafaznv/nova-map-field#24]
The search box has disappeared from a map field that had it working before.

When I open the Edit view for the resource that has the map field, I see the following error in my console:
`Error in console: TypeError: Cannot call a class constructor without [new]`

Using version 1.7.3 under Nova 4.19.0

Any idea where to look, what to investigate/check?

Thanks!!

**Comment by mostafaznv** [comment]
Hi @wdelfuego 

Thanks for the report.
I fixed it. please update to the latest version.

**Comment by wdelfuego** [comment]
Yes, this works for me now :)
Thanks for your quick fix, great support 👌
