### ISSUE TITLE
Multi Polygon

### ISSUE THREAD

**Issue by brandonkhj** [mostafaznv/nova-map-field#3]
Hi, Nice package. Any plan on integrating multi polygon?

**Comment by mostafaznv** [comment]
Hi @brandonkhj 

Yes, I will support most of these types in future versions.

**Comment by brandonkhj** [comment]
Any estimated timeline?

**Comment by mostafaznv** [comment]
Now you can use multi-polyon fields.
Just update to [1.2.0](https://github.com/mostafaznv/nova-map-field/tree/1.2.0)
