### ISSUE TITLE
caching config causing search provider failure

### ISSUE THREAD

**Issue by mziraki** [mostafaznv/nova-map-field#30]
after "php artisan config:cache" when you enter an address on search input it fails because of these two cached config

nova-map-field.php:
`'provider' => \Mostafaznv\NovaMapField\DTOs\MapSearchProvider::OSM(),`
and
`'box-type' => \Mostafaznv\NovaMapField\DTOs\MapSearchBoxType::TEXT_FIELD(),`

and can be fixed temporary via using "searchProvider" method directly in nova resources.

**Comment by mostafaznv** [comment]
Hi @mziraki 
Thanks for reporting this bug.
Update the package to [v1.8.1](https://github.com/mostafaznv/nova-map-field/releases/tag/1.8.1).
