### ISSUE TITLE
Change point not working

### ISSUE THREAD

**Issue by osama-klabs** [mostafaznv/nova-map-field#35]
Laravel : 9
php: 8.0.2
nova: 4
Nova Map Field: 2.0.0
matanyadaev/laravel-eloquent-spatial: 2.10

After i select location then i am unable to change the marker

```
MapPointField::make('Location', 'map_location')
                ->defaultLatitude('26.0692242')
                ->defaultLongitude('50.606998')
                ->markerIcon(1)
                ->zoom(10.83)
                ->required()
                ->requiredOnCreate()
                ->withoutZoomSlider()
                ->hideDetailButton()
                ->withoutZoomControl(),
```

Migrations: 

```
$table->point('map_location')->nullable();
```

Details:
I opened create resource page then select my desired location then i am trying to change the location (means marker) it is not updating

Also in update resource user not able to change location

**Comment by mostafaznv** [comment]
Please tell me version of `Nova Map Field` package.
And what type of field are you using? Point? Polygon? MultiPolygon?
Give me more details about the situation.

**Comment by osama-klabs** [comment]
field: MapPointField
Nova Map Field: 2.0.0

**Comment by mostafaznv** [comment]
It works.
You should drag the marker.

Like this:
[map.webm](https://user-images.githubusercontent.com/7619687/218129664-860927c5-4eb7-494d-95ac-a35ecb1329a0.webm)

**Comment by Synchro** [comment]
The thing I have found confusing about the current arrangement is that you have to drag the blue dot, not the red marker. I'm not sure why we need the blue dot?

**Comment by mostafaznv** [comment]
> The thing I have found confusing about the current arrangement is that you have to drag the blue dot, not the red marker. I'm not sure why we need the blue dot?

I have no idea 😄
it's a decision by `open-layers` map developer.
I'll look into it to check if there is a workaround to change this behavior.
