### ISSUE TITLE
DependsOn?

### ISSUE THREAD

**Issue by couchlab-pl** [mostafaznv/nova-map-field#39]
Want to show/hide map fields dependsOn place type select. For now it's not possible, need to have 3 maps on one form.

Maybe it's easy to add dependsOn just for hide/show?

**Comment by mostafaznv** [comment]
Hi @couchlab-pl 
Thanks for the report.
Now all map fields are supporting dependent field.

```php
MapMultiPolygonField::make(trans('Areas'), 'areas')
    ->hide()
    ->dependsOn('title', function (MapMultiPolygonField $field, NovaRequest $request, FormData $formData) {
        if ($formData->string('title') != '') {
            $field->show()->rules('required');
        }
    })
```

And other fields can also be dependent on map fields.
Please update the package to [v3.1.0](https://github.com/mostafaznv/nova-map-field/releases/tag/3.1.0)
