### ISSUE TITLE
Url for search is invalid due to api change

### ISSUE THREAD

**Issue by Thorazine** [mostafaznv/nova-map-field#41]
Apparently there has been a change in the API for open street map. The result is shown when directly accessing a search url like so: https://nominatim.openstreetmap.org/search/?q=something

With their new change you are required to drop the slash like so: https://nominatim.openstreetmap.org/search?q=something

The result now is that a search will trigger a 404 with an error like: "Error! No internet connection?"

**Comment by Synchro** [comment]
Ah, I've seen that and wondered what was going on!

**Comment by mostafaznv** [comment]
Thank you for reporting the issue. I will look into it tomorrow.

**Comment by Thorazine** [comment]
There is an easy temp fix for everybody that does not use a build process in their deploy line. On your server go to the vendor/mostafaznv/nova-map-field/dist/js/field.js and search for "https://nominatim.openstreetmap.org/search/". Remove the trailing slash and your done until the next time you update this composer package. Only requires a refresh of your page, no build.

**Comment by mostafaznv** [comment]
Apologies for the late response. It has been a busy and long day.

I have investigated the issue and found that it is a bug in the upstream package ([ol-geocoder](https://github.com/kirtan-desai/ol-geocoder)). I have submitted a PR to address the problem, and I hope they will merge it soon.

In the meantime, I have published a temporary solution, and you can use it with the upcoming release.

**Comment by isoleenta** [comment]
Thank you so much. You helped me too)

**Comment by msabahDatac** [comment]
I fixed this issue by 

1-https://github.com/mostafaznv/nova-map-field/issues/41#issuecomment-1666772591
or
2- $:   composer update mostafaznv/nova-map-field

Thanks  @Thorazine

**Comment by mostafaznv** [comment]
fixed.
please update to [3.1.2](https://github.com/mostafaznv/nova-map-field/releases/tag/3.1.2)
