### ISSUE TITLE
Longitude and Latitude misrepresentation on show details modal

### ISSUE THREAD

**Issue by geekdanitek** [mostafaznv/nova-map-field#48]
There is a value mismatch on the show details modal for longitude and latitude. The value of longitude is shown as latitude. Taking a code deep dive using the screenshot below shows the coordinate assignment when compared with the database value as index zero for longitude and index one for latitude. 
![Screenshot 2024-02-14 at 08 39 42](https://github.com/mostafaznv/nova-map-field/assets/32544367/bf0a69a1-b5e7-4b75-a66d-72dccb4705af)

Using the screenshot below, it can be seen on the frontend that index zero is used for latitude instead of longitude.
![Screenshot 2024-02-14 at 08 58 20](https://github.com/mostafaznv/nova-map-field/assets/32544367/36cc5185-8359-422a-a75a-47d86d4deaf2)

**Comment by mostafaznv** [comment]
Hi @geekdanitek 

Thank you for your report.

Are you encountering any issues with this package? Specifically, are the displayed results on your details page (lat/lng fields and map) mismatched?

According to the `laravel-eloquent-spatial` package, the first argument of the `Point` object represents `latitude`, and the second one is for `longitude`.


https://github.com/MatanYadaev/laravel-eloquent-spatial/blob/eac8c0758519ee54c9af6d4425d5248d2670fcf9/src/Objects/Point.php#L15



Therefore, I believe there shouldn't be any problem displaying lat/lng data on the Nova panel.
