### ISSUE TITLE
Capture - file path misses the model's id

### ISSUE THREAD

**Issue by marlocorridor** [mostafaznv/nova-map-field#55]
Hi @mostafaznv, this `capture` experimental feature is great! 

My issue is that the file path will be the intended after the $model has an ID value. 
You might already know this issue.

https://github.com/mostafaznv/nova-map-field/blob/dea7f47aa56354f11f0313ba817de7bb7f9eae2c/src/Traits/CapturesScreenshot.php#L11

https://github.com/mostafaznv/nova-map-field/blob/dea7f47aa56354f11f0313ba817de7bb7f9eae2c/src/Fields/MapPointField.php#L49

I'm not sure how to execute the saving of file after the record is saved. My help could be just to list it here on the issues.
 
🚀 Thanks for this package!

on Laravel v11

**Comment by mostafaznv** [comment]
Hi @marlocorridor,

Could you please provide further details about the issue? What is your main concern with the current type of file paths, and what are your expectations regarding them?

I can change `storeScreenshot` from `private` to `protected`, allowing you to make your customizations. However, for now, I'd like to identify the exact problem with the current paths. If it's a common issue, I'll work on finding a solution for it.
