### ISSUE TITLE
marker not visible

### ISSUE THREAD

**Issue by vesper8** [mostafaznv/nova-map-field#8]
Hi there, first of all thanks a lot for making this package. I was previously using `davidpiesse/nova-map` but that broke when I upgraded to Nova v4 so now I'm trying out yours.

I have it setup and the map is showing and I can tell that the lng/lat values are correctly being read from my location point because the correct map is loading. However I was expecting to see a marker show up on the exact coordinates and I'm not seeing any marker appear at all.

I have it set up like this:

```

MapPointField::make('Current City', 'current_city_location')
            ->zoom(15)
            ->withoutZoomSlider()
            ->markerIcon(2)
```

I tried values 1, 2 and 3 in `markerIcon` but that doesn't seem to change anything.

I tried it with and without the `use HasSpatialColumns;` on my model that has the `current_city_location` field and either way the map shows up fine and the marker doesn't

I'm using this in combination with your `"matanyadaev/laravel-eloquent-spatial": "^2.0",` package.

Any idea why I can't see a marker?

Many thanks!

**Comment by mostafaznv** [comment]
Hi @vesper8 


To publish `assets` and `config file`, you should run this command:

```bash
php artisan vendor:publish --provider="Mostafaznv\NovaMapField\NovaMapFieldServiceProvider"
```

Did you do it?

**Comment by vesper8** [comment]
Oops! I forgot that step.. that totally fixed the missing marker! Thank you!
